# Generated by Django 3.1.4 on 2020-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
